import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const leagueSpartan = League_Spartan({ subsets: ["latin"], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] });

export const metadata: Metadata = {
  title: "Docunder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
        <main className="flex min-h-screen min-w-full flex-col items-center">
          <Header/>
          <nav className="w-full h-full">
            {children}
          </nav>
        </main>
      </body>
    </html>
  );
}
